apiVersion: apps/v1
kind: Deployment
metadata:
  name: myjavaapp-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myjavaapp
  template:
    metadata:
      labels:
        app: myjavaapp
    spec:
      containers:
      - name: myjavaapp
        image: 801646209932.dkr.ecr.us-east-1.amazonaws.com/devops-docker-image
        ports:
        - containerPort: 8085

---
apiVersion: v1
kind: Service
metadata:
  name: myjavaapp-service
spec:
  selector:
    app: myjavaapp
  ports:
  - name: http
    port: 80
    targetPort: 8085
  type: LoadBalancer
